Careerportal/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    path("accounts/", include("registration.backends.default.urls")),
]

myapp/urls.py
from django.urls import path
from myapp.views import home,create_job,JobListByIndustryView,apply_job,success,industry_list,otp,login,logout,register,Aboutus,Contactus,Footer
app_name="myapp"
urlpatterns=[
    path('',home,name='home'),
    path('jobs/create/', create_job, name='create_job'),
    path('industry/<int:pk>/jobs/', JobListByIndustryView.as_view(), name='job_list_by_industry'),
    path('apply_job/<int:industry_id>/<int:job_id>/', apply_job, name='apply_job'),
    path('success/',success,name='success'),
    path('industries/', industry_list, name='industry_list'),
    path('otp/<str:otp>/<str:username>/<str:password>/<str:email>/',otp, name='otp'),
    path('login/',login,name='login'),
    path('logout/',logout,name='logout'),
    path('register/',register,name='register'),
    path('About /',Aboutus,name='About us'),
    path('Contact /',Contactus,name='Contact us'),
    path('Footer /',Footer,name='footer'),
]

myapp/models.py
from django.contrib.auth.models import User
from django.db import models
class Industry(models.Model):
    #user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name
    
class Job(models.Model):
    title = models.CharField(max_length=255)
    Description=models.TextField()
    JobType = models.CharField(max_length=255)
    industry = models.ForeignKey(Industry, on_delete=models.CASCADE)
    Companyname = models.CharField(max_length=200)
    salary = models.CharField(max_length=300)
    Location=models.CharField(max_length=200)

    def __str__(self):
        return self.title
    

class JobApplication(models.Model):
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    resume = models.FileField(upload_to='resumes/')
    cover_letter = models.TextField()

    def __str__(self):
        return f"Application for {self.job.title} by {self.name}"

myapp/forms.py
from .models import Job
from django import forms
class JobForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = '__all__'
from .models import JobApplication

class JobApplicationForm(forms.ModelForm):
    class Meta:
        model = JobApplication
        fields = ['name', 'email', 'resume', 'cover_letter']

# forms.py

from django import forms
from .models import Industry

class IndustryForm(forms.ModelForm):
    class Meta:
        model = Industry
        fields = ['name']  # Add other fields as needed

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Add any additional customization for your form fields here

myapp/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User,auth
from django.contrib import auth
from django.core.mail import send_mail
from django.contrib.auth import authenticate,login
from django.http import HttpResponse
from django.contrib import messages
from django.core.mail import send_mail

import random
from django.urls import reverse
from .models import Industry, Job
from .forms import JobForm, JobApplicationForm

def Aboutus(request):
    return render(request,'About us.html')
def Contactus(request):
        return render(request,'Contact us.html')

def home(request):
    return render(request, 'home.html')

def Footer(request):
    return render(request, 'footer.html')

def create_job(request):
    if request.method == 'POST':
        form = JobForm(request.POST)
        if form.is_valid():
            job = form.save()
            return redirect('job_detail', job_id=job.id)
    else:
        form = JobForm()
    return render(request, 'create_job.html', {'form': form})

class JobListByIndustryView(View):
    template_name = 'job_list_by_industry.html'

    def get(self, request, pk):
        industry = get_object_or_404(Industry, pk=pk)
        jobs = Job.objects.filter(industry=industry)
        return render(request, self.template_name, {'industry': industry, 'jobs': jobs})
from django.shortcuts import render, redirect
from django.http import HttpResponse
from myapp.models import Job, Industry, JobApplication
from django.core.exceptions import ValidationError


def apply_job(request, industry_id, job_id):
    if request.method == 'POST':
        full_name = request.POST.get('full_name')
        email = request.POST.get('email')
        resume = request.FILES.get('resume')
        cover_letter = request.POST.get('cover_letter')
        print(full_name)
        print(email)
        print(resume)
        job_application = JobApplication.objects.create(
            job_id=job_id,
            name=full_name,
            email=email,
            resume=resume,
            cover_letter=cover_letter,
        )
        job_application.save()
        # Optionally, you can add additional logic here, like sending a confirmation email to the applicant
        return redirect('myapp:success')  # Redirect to a success page after submission
    else:
        context = {
            'job': Job.objects.get(pk=job_id),
            'industry': Industry.objects.get(pk=industry_id),
        }
        return render(request, 'job_application_form.html', context)


def success(request):
    return render(request, 'success.html')

from django.shortcuts import render
from .models import Industry

def industry_list(request):
    industries = Industry.objects.all()
    return render(request, 'industry_list.html', {'industries': industries})

def send_otp(email, otp):
    subject = 'OTP Verification'
    message = f'Your OTP for registration is: {otp}'
    send_mail(subject, message, None, [email])



#def create_sector(request, industry_id):
#   industry = get_object_or_404(Industry, pk=industry_id)
#
#   if request.method == 'POST':
#      form = IndustryForm(request.POST)
#     if form.is_valid():
#        sector = form.save(commit=False)
#       sector.industry = industry
#      sector.save()
#     return redirect('industry_detail', pk=industry.id)

#else:
#   form = IndustryForm()

    #return render(request, 'create_sector.html', {'industry': industry, 'form': form})

from django.http import HttpResponseRedirect

# ...

def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]
        password = request.POST["password"]
        password2 = request.POST["password2"]

        if User.objects.filter(username=username).exists():
            messages.error(request, "Username already taken")
            return redirect('myapp:register')

        otp_number = random.randint(1000, 9999)
        otp = str(otp_number)

        send_otp(email, otp)
        request.session['username'] = username
        request.session['email'] = email
        request.session['password'] = password
        request.session['otp'] = otp  # Add this line to store OTP in the session

        # Construct the URL using HttpResponseRedirect
        #return HttpResponseRedirect(f'/otp/{otp}/{username}/{password}/{email}/')
        # Alternatively, you can use reverse:
        return HttpResponseRedirect(reverse('myapp:otp', args=[otp, username, password, email]))

    else:
        return render(request, 'register.html')


def otp(request, otp, username, password, email):
    if request.method == "POST":
        uotp = request.POST['otp']
        otp_from_session = request.session.get('otp')

        if uotp == otp_from_session:
            username = request.session.get('username')
            email = request.session.get('email')
            password = request.session.get('password')

            user = User.objects.create_user(username=username, password=password, email=email)
            user.save()
            return redirect('myapp:login')
        else:
            messages.error(request, 'Invalid OTP. Please try again.')
            return redirect('myapp:otp', otp=otp, username=username, password=password, email=email)

    return render(request, 'otp.html',{'otp': otp, 'username': username, 'password': password, 'email': email})



def login(request):
    if request.method=="POST":
        username=request.POST['username']
        password=request.POST['password']
        user=auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            return redirect('myapp:industry_list')
        else:
            messages.info(request,'Invalid user credentials')
            return redirect('myapp:login')
    else:
        return render(request,'login.html')

def logout(request):
    auth.logout (request)
    return redirect('/')

myapp/templates/About us.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<style>
    /*---------------------------------------
   Social section
-----------------------------------------*/
    footer {
      padding: 0px 0px 0px 0px;
      background-color: black;
      margin: 0px;
    }

    .fa {
      padding: 20px;
      font-size: 23px;
      width: 60px;
      text-align: center;
      text-decoration: none;
      margin: 5px 2px;
      border-radius: 50%;
    }

    .fa:hover {
      opacity: 0.5;
      text-decoration: none;
    }

    .fa-facebook {
      background: #3B5998;
      color: white;
      margin-top: 30px;
    }

    .fa-whatsapp {
      background: #25d366;
      color: white;
    }

    .fa-twitter {
      background: #55ACEE;
      color: white;
    }

    .fa-instagram {
      background: #125688;
      color: white;
    }

    p {
      text-align: center;

    }
  </style>
<body>
    <div>
        <center><h3 class='alert alert-success' style="margin-bottom:0px;">About Us !</h3></center><br>
        <center>
        <div class="jumbotron" style="margin-bottom: 0px;margin-top: 0px;">
          <br><br>
            <h1 class="display-4">Hello</h1>
            <br><br><Br><Br>
            <p class="lead">A service dedicated to Users. We provide online resources, professional support
              and guidance to all our users whenever, and from wherever they have choosen to apply job.</p>
            <hr class="my-4">
            <p>Explore our Website.</p>
            <p class="lead">
              <a class="btn btn-primary btn-lg" href="/" role="button">HOME</a>
            </p>
          </div>
        </center>
    </div>
</body>
</html>

myapp/templates/Contact us.html
<style>
  .mydivstyle:hover{
    box-shadow: 0 0 20px 0 rgba(0, 0, 0.3); width: 300px;
    transform: translatey(20px);
    border-left-width: 20px;
    border-left-width: 20px;
  }
  
</style>

<center>
{% block content %}
<div class="container" style="margin-top: 50px;">
    <h1 class="text-center">Contact Us</h1>
    <div class="row mt-5 text-center"><br>
      <div class="col-lg-3 col-sm-6 mydivstyle">
        <h4><i class="fas fa-phone-square"><img src="https://static.vecteezy.com/system/resources/previews/000/615/758/original/vector-call-icon.jpg" height="25px" width="25px"><br> Contact</i></h4>
        <p class="text-danger font-weight-bold">+916304337967</a></p>
      </div>
      <br>
      <div class="col-lg-3 col-sm-6 mydivstyle">
        <h4><i class="fa fa-envelope"><img src="https://static.vecteezy.com/system/resources/previews/000/581/545/original/email-icon-vector-illustration.jpg" height="15px" width="15px"><br></i> Send-email</h4>
        <p class="text-danger font-weight-bold">Careerhub@gmail.com</a></p>
      </div>
      <br>
      <div class="col-lg-3 col-sm-6 mydivstyle">
        <h4><i class="fa fa-address-card" aria-hidden="true"><img src="https://tse2.mm.bing.net/th?id=OIP.MOxzgC1DPe9MDBLr4u-GhQHaHv&pid=Api&P=0&h=180" height="25px" width="25px"><br></i> Office Address</h4>
        <p class="text-danger font-weight-bold"><a href="https://www.google.co.in/maps/place/Vijayawada,+Andhra+Pradesh/@16.5103132,80.5624821,12z/data=!3m1!4b1!4m6!3m5!1s0x3a35eff9482d944b:0x939b7e84ab4a0265!8m2!3d16.5061743!4d80.6480153!16zL20vMDM4NWs3?entry=ttu">Vijayawada,India</a></p>
      </div>
      <br>
      <div class="col-lg-3 col-sm-6 mydivstyle">
        <h4><i class="fa fa-address-card" aria-hidden="true"><img src="https://pluspng.com/img-png/time-png-png-ico-icns-more-1024.png" height="35px" width="35px"><br></i> Web Site</h4>
        <p>All time avaliable</p>
      </div>
    <div>
        <h4 class="lead">
            <a class="btn btn-primary btn-lg" href="/" role="button">HOME</a>
    </h4>
    </div>
  </div>
</div>
  
{% endblock content %}
</center>

myapp/templates/apply_job.html
<!-- apply_job.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Apply for Jobs</title>
</head>
<body>
    <h2>{{ industry.name }} Jobs</h2>
    <ul>
        {% for job in jobs %}
            <li>
                <strong>{{ job.title }}</strong>
                <p>{{ job.description }}</p>
                <!-- Add more job details as needed -->

                <!-- Create a form for job application -->
                <form method="post" action="{% url 'myapp:apply_job' industry_id=industry.id %}">
                    {% csrf_token %}
                    <input type="hidden" name="job_id" value="{{ job.id }}">
                    <button type="submit">Apply</button>
                </form>
            </li>
        {% endfor %}
    </ul>
</body>
</html>

myapp/templates/base.html
{% load static %}
<!--!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, 
    initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
</head>
<style> 
  body{
      background-image: url('https://images3.alphacoders.com/424/42405.jpg');
      height:"100%";
      margin: 0;
      background-repeat: no-repeat;
      background-size: cover; /* Set background size to cover the entire screen */
      background-attachment: fixed; /* Optional: Fix the background while scrolling */
  }
  </style>
<body>
    <nav style="background-color:rgba(150, 138, 70, 0.804);" class="navbar navbar-expand-lg navbar-light">
        <b><a class="navbar-brand" href="#">    career portal</a></b>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="#">About</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
                Features
              </a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="#">Company Login</a>
                <a class="dropdown-item" href="#">Admin Login</a>
                <a class="dropdown-item" href="#">User Login</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Contact us</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" name="q" value="{{request.GET.q}}" placeholder="Search" aria-label="Search">
          </form>
          <a class="btn btn-primary" href="{% url 'myapp:login' %}">Login</a>&nbsp;
          <a class="btn btn-primary" href="{% url 'myapp:register' %}">Register</a>&nbsp;
          <a class="btn btn-primary" href="#">Logout</a>
          
        </div>
      </nav>
  <div class="container">
    <br>
{% block content %}

{% endblock %}
</div>
</body>
</html-->



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detail Page</title>
</head>
<style>
    body{
        background-image: url("https://cdn.wallpapersafari.com/68/93/hSEvPY.jpg");
        background-repeat: no-repeat;
        background-size: cover;
    
    }

    *{
        margin:0px;
        padding: 0px;
    }
    body{
        font-family: 'Nunito Sans', sans-serif;
    }
    .cards{
        width:15%;
        display: inline-block;
        background-color: aliceblue;
        border-radius: 5px;
        margin: 55px;
        box-shadow: 2px 2px 10px black;
    }
    .image img{
        width:100%;
        height: 50;
        border-radius: 50%;
    }
    .title{
        text-align: center;
        padding: 5px;
    }
    .des{
        text-align: center;
        padding: 4px;
    }
    button{
        margin-top: 10px;
        margin-bottom: 20px;
        background-color:blue;
        color: white;
        border: 1px solid black;
        padding:10px;
        border-radius: 5px;
        cursor: pointer;
        font-size: 15px;
        font-family: 'Nunito Sans', sans-serif;

    }
    button:hover{
        background-color:green;
        color: black;
        transition: .5s; 
    }
    .title{
        margin-top:5%;
        top:50%;
        left: 50%;
        font-family: 'Nunito Sans', sans-serif;
    }
    .title h1{
        color:whitesmoke;
        font-size: 40px;
    }
</style>
<body>
    <div class="title">
        <h1>Login/Register</h1>
    </div>

    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
     <div class="cards">
        <div class="image">
            <img src="https://tse4.mm.bing.net/th?id=OIP.gDTdfEP9CkRFtJHvAee1wgAAAA&pid=Api&P=0&h=180" width="100" height="200">
        </div>
        <div class="des">
            <a href="{% url 'myapp:login' %}"><button>Login</button></a>
        </div>
    </div>
    <div class="cards">
        <div class="image">
            <img src="https://cdn2.sportngin.com/attachments/photo/40d3-121410675/register-button_large.png" width="100" height="200">
        </div>
        <div class="des">
            <a href="{% url 'myapp:register' %}"><button>Register</button></a>
        </div>
    </div>
</body>
</html>

myapp/templates/create_job.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Job</title>
</head>
<body>
    <h2>Create a New Job</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create Job</button>
    </form>
</body>
</html>

myapp/templates/create_sector.html
{% extends 'base.html' %}

{% block content %}
  <h2>Create Sector for {{ industry.name }}</h2>

  <form method="post" action="{% url 'create_sector' industry_id=industry.id %}">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Create Sector</button>
  </form>

  <a href="{% url 'industry_detail' pk=industry.id %}">Back to Industry Details</a>
{% endblock %}

myapp/templates/industry_list.html
{% csrf_token %}
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>All Industries</title>
   <!-- Add Bootstrap CSS link -->
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
   <style>
      body {
         background-color: #f8f9fa;
      }
      .container {
         margin-top: 50px;
      }
      .company-card {
         border: 1px solid #dee2e6;
         border-radius: 10px;
         margin-bottom: 20px;
         padding: 20px;
         background-color: #ffffff;
      }
      .company-card:hover{
         box-shadow: 0 0 20px 0 rgba(0, 0, 0.3); width: 500px;
         transform: translatey(20px);
         border-left-width: 20px;
         border-left-width: 20px;
  }
   </style>
</head>
<body>
   <div class="container">
      <h2 class="text-center mb-4">Types of Industry and Careers You Can Pursue Within Them</h2>
      <div class="row">
         {% for industry in industries %}
            <div class="col-md-6">
               <div class="card company-card">
                  <div class="card-body">
                     <h5 class="card-title">{{ industry.name }}</h5>
                     <p class="card-text">{{ industry.description }}</p>
                     <!-- Add more industry details as needed -->
                     <!-- Create a hyperlink to the job list for the industry -->
                     <a href="{% url 'myapp:job_list_by_industry' pk=industry.id %}" class="btn btn-primary">View Sectors</a>
                  </div>
               </div>
            </div>
         {% endfor %}
      </div>
   </div>

   <!-- Add Bootstrap JS and Popper.js scripts -->
   <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
   <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

myapp/templates/job_application_form.html
<!-- job_application_form.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Job Application Form</title>
    <!-- Add Bootstrap CSS link -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <style>
        body {
            background-color: #f8f9fa;
            padding: 20px;
        }
        .application-form {
            max-width: 600px;
            margin: 0 auto;
            background-color: #ffffff;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        .form-group {
            margin-bottom: 20px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2 class="text-center">Apply for {{ job.title }} at {{ industry.name }}</h2>
        <form class="application-form" method="post" action="{% url 'myapp:apply_job' industry_id=industry.id job_id=job.id %}">
            {% csrf_token %}
            
            <!-- Personal Information -->
            <div class="form-group">
                <label for="full_name">Full Name</label>
                <input type="text" class="form-control" id="full_name" name="full_name" placeholder="John Doe" required>
            </div>

            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="john@example.com" required>
            </div>

            <!-- Resume/CV Upload -->
            <div class="form-group">
                <label for="resume">Resume/CV (PDF)</label>
                <input type="file" class="form-control-file" id="resume" name="resume" accept=".pdf" required>
            </div>

            <!-- Additional Questions or Cover Letter -->
            <div class="form-group">
                <label for="cover_letter">Cover Letter (optional)</label>
                <textarea class="form-control" id="cover_letter" name="cover_letter" rows="4" placeholder="Write your cover letter here"></textarea>
            </div>

            <!-- Submit Button -->
            <button type="submit" class="btn btn-primary">Submit Application</button>
        </form>
    </div>

    <!-- Add Bootstrap JS and Popper.js scripts -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

myapp/templates/job_list_by_industry.html
<!-- apply_job.html -->
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>{{ industry.name }} Jobs</title>
   <!-- Add Bootstrap CSS link -->
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body>
   <div class="container mt-4">
      <h2>{{ industry.name }} Jobs</h2>
      <div class="row">
         {% for job in jobs %}
            <div class="col-md-6 mb-4">
               <div class="card">
                  <div class="card-body">
                     <h5 class="card-title">{{ job.title }}</h5>
                     <p class="card-text">{{ job.description }}</p>
                     <ul class="list-group list-group-flush">
                        <li class="list-group-item"><strong>Description:</strong> {{ job.Description }}</li>
                        <!--<li class="list-group-item"><strong>Requirements:</strong> {{ job.Requirements }}</li>-->
                        <li class="list-group-item"><strong>JobType:</strong> {{ job.JobType }}</li>
                        <li class="list-group-item"><strong>Companyname:</strong> {{ job.Companyname }}</li>
                        <li class="list-group-item"><strong>Salary:</strong> {{ job.salary }}</li>
                        <li class="list-group-item"><strong>Location:</strong> {{ job.Location }}</li>
                        <!-- Add more job details as needed -->
                     </ul>
                     <!-- Create a hyperlink to the job application form -->
                     <a href="{% url 'myapp:apply_job' industry_id=industry.id job_id=job.id %}" class="btn btn-primary">Apply now</a>
                     <p>For more details:<a href="{% url 'myapp:Contact us' %}" class="btn btn-primary">Contact Us</a></p>
                  </div>
               </div>
            </div>
         {% endfor %}
      </div>
   </div>

   <!-- Add Bootstrap JS and Popper.js scripts -->
   <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
   <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

myapp/templates/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<br><br><br>
<center>
<body>
    <img src="https://career.qpage.one/arts/success.png" alt="">
     <h1>Applied Successfully!!!!......</h1>
    <p>All the best for your bright future🤗</p>
</body></center>
</html>